Map<String, String> assets = {
  'logo': 'https://plincogame.com/assets/images/Logo_Plinco.png',
  'bg': 'https://plincogame.com/assets/images/bg.png',
  'level_1_bg': 'https://plincogame.com/assets/images/levels/level_1_bg.png',
  'level_2_bg': 'https://plincogame.com/assets/images/levels/level_2_bg.png',
  'level_3_bg': 'https://plincogame.com/assets/images/levels/level_3_bg.png',
  'level_4_bg': 'https://plincogame.com/assets/images/levels/level_4_bg.png',
  'level_1_preview': 'https://plincogame.com/assets/images/levels/level_1_preview.png',
  'level_2_preview': 'https://plincogame.com/assets/images/levels/level_2_preview.png',
  'level_3_preview': 'https://plincogame.com/assets/images/levels/level_3_preview.png',
  'level_4_preview': 'https://plincogame.com/assets/images/levels/level_4_preview.png',
  'back_btn': 'https://plincogame.com/assets/images/buttons/back_btn.png',
  'home_btn': 'https://plincogame.com/assets/images/buttons/home_btn.png',
  'play_btn': 'https://plincogame.com/assets/images/buttons/play_btn.png',
  'settings_btn': 'https://plincogame.com/assets/images/buttons/settings_btn.png',
  'left_menu_btn': 'https://plincogame.com/assets/images/buttons/left_menu_btn.png',
  'right_menu_btn': 'https://plincogame.com/assets/images/buttons/right_menu_btn.png',
  'main_menu_btn': 'https://plincogame.com/assets/images/buttons/main_menu_btn.png',
  'ball_decoration': 'https://plincogame.com/assets/images/elements/ball_decoration.png',
  'ball_icon': 'https://plincogame.com/assets/images/elements/ball_icon.png',
  'coin_icon': 'https://plincogame.com/assets/images/elements/coin_icon.png',
  'filled_star': 'https://plincogame.com/assets/images/elements/filled_star.png',
  'stars': 'https://plincogame.com/assets/images/elements/stars.png',
};
