Map<String, String> assetsMap = {
  'bg': '/assets/images/bg.png',
  'logo': '/assets/images/Logo_Plinco.png',
  'level_1_bg': '/assets/images/levels/level_1_bg.png',
  'level_2_bg': '/assets/images/levels/level_2_bg.png',
  'level_3_bg': '/assets/images/levels/level_3_bg.png',
  'level_4_bg': '/assets/images/levels/level_4_bg.png',
  'level_1_preview': '/assets/images/levels/level_1_preview.png',
  'level_2_preview': '/assets/images/levels/level_2_preview.png',
  'level_3_preview': '/assets/images/levels/level_3_preview.png',
  'level_4_preview': '/assets/images/levels/level_4_preview.png',
  'back_btn': '/assets/images/buttons/back_btn.png',
  'home_btn': '/assets/images/buttons/home_btn.png',
  'play_btn': '/assets/images/buttons/play_btn.png',
  'settings_btn': '/assets/images/buttons/settings_btn.png',
  'left_menu_btn': '/assets/images/buttons/left_menu_btn.png',
  'right_menu_btn': '/assets/images/buttons/right_menu_btn.png',
  'main_menu_btn': '/assets/images/buttons/main_menu_btn.png',
  'ball_decoration': '/assets/images/elements/ball_decoration.png',
  'ball_icon': '/assets/images/elements/ball_icon.png',
  'coin_icon': '/assets/images/elements/coin_icon.png',
  'filled_star': '/assets/images/elements/filled_star.png',
  'stars': '/assets/images/elements/stars.png',
  'gun': '/assets/images/elements/gun.png',
  'gun_back': '/assets/images/elements/gun_back.png',
  'ball': '/assets/images/elements/ball.png',
};
